# permissions for end users to view instances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: instance-viewer-role
rules:
- apiGroups:
  - infrastructure.cloudprovider.io
  resources:
  - instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cloudprovider.io
  resources:
  - instances/status
  verbs:
  - get
