# permissions for end users to edit instances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: instance-editor-role
rules:
- apiGroups:
  - infrastructure.cloudprovider.io
  resources:
  - instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cloudprovider.io
  resources:
  - instances/status
  verbs:
  - get
