---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - infrastructure.cloudprovider.io
  resources:
  - instancestacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cloudprovider.io
  resources:
  - instancestacks/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.cloudprovider.io
  resources:
  - instancestacks/status
  verbs:
  - get
  - patch
  - update
